/* 
DROP DATABASE IF EXISTS xiptodb;
CREATE DATABASE xiptodb;

Automatic execution when the server startups:
*/

ALTER TABLE Category
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE User
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE Experience
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE Review
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;