--run this before start the server
DROP DATABASE IF EXISTS xiptodb;
CREATE DATABASE xiptodb;


--run these after start the server (if is in test mode)
USE xiptodb;

ALTER TABLE Category
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE User
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE Experience
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE Review
CHANGE COLUMN createdAt createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN updatedAt updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;
